//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StudentskaEvidencijaModel", "FK_Ispit_Predmet", "Predmet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StudentskaEvidencija.Models.Predmet), "Ispit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentskaEvidencija.Models.Ispit), true)]
[assembly: EdmRelationshipAttribute("StudentskaEvidencijaModel", "FK_Predmet_Smer", "Smer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StudentskaEvidencija.Models.Smer), "Predmet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentskaEvidencija.Models.Predmet), true)]
[assembly: EdmRelationshipAttribute("StudentskaEvidencijaModel", "PredmetProfesor", "Predmet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentskaEvidencija.Models.Predmet), "Profesor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentskaEvidencija.Models.Profesor))]
[assembly: EdmRelationshipAttribute("StudentskaEvidencijaModel", "FK_Ispit_Student", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StudentskaEvidencija.Models.Student), "Ispit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentskaEvidencija.Models.Ispit), true)]
[assembly: EdmRelationshipAttribute("StudentskaEvidencijaModel", "FK_Student_Smer", "Smer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StudentskaEvidencija.Models.Smer), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentskaEvidencija.Models.Student), true)]
[assembly: EdmRelationshipAttribute("StudentskaEvidencijaModel", "FK_Ispit_Profesor", "Profesor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StudentskaEvidencija.Models.Profesor), "Ispit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentskaEvidencija.Models.Ispit), true)]

#endregion

namespace StudentskaEvidencija.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StudentskaEvidencijaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StudentskaEvidencijaEntities object using the connection string found in the 'StudentskaEvidencijaEntities' section of the application configuration file.
        /// </summary>
        public StudentskaEvidencijaEntities() : base("name=StudentskaEvidencijaEntities", "StudentskaEvidencijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudentskaEvidencijaEntities object.
        /// </summary>
        public StudentskaEvidencijaEntities(string connectionString) : base(connectionString, "StudentskaEvidencijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudentskaEvidencijaEntities object.
        /// </summary>
        public StudentskaEvidencijaEntities(EntityConnection connection) : base(connection, "StudentskaEvidencijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ispit> Ispits
        {
            get
            {
                if ((_Ispits == null))
                {
                    _Ispits = base.CreateObjectSet<Ispit>("Ispits");
                }
                return _Ispits;
            }
        }
        private ObjectSet<Ispit> _Ispits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Korisnik> Korisniks
        {
            get
            {
                if ((_Korisniks == null))
                {
                    _Korisniks = base.CreateObjectSet<Korisnik>("Korisniks");
                }
                return _Korisniks;
            }
        }
        private ObjectSet<Korisnik> _Korisniks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profesor> Profesors
        {
            get
            {
                if ((_Profesors == null))
                {
                    _Profesors = base.CreateObjectSet<Profesor>("Profesors");
                }
                return _Profesors;
            }
        }
        private ObjectSet<Profesor> _Profesors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Smer> Smers
        {
            get
            {
                if ((_Smers == null))
                {
                    _Smers = base.CreateObjectSet<Smer>("Smers");
                }
                return _Smers;
            }
        }
        private ObjectSet<Smer> _Smers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Predmet> Predmets
        {
            get
            {
                if ((_Predmets == null))
                {
                    _Predmets = base.CreateObjectSet<Predmet>("Predmets");
                }
                return _Predmets;
            }
        }
        private ObjectSet<Predmet> _Predmets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ispits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIspits(Ispit ispit)
        {
            base.AddObject("Ispits", ispit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Korisniks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKorisniks(Korisnik korisnik)
        {
            base.AddObject("Korisniks", korisnik);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profesors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfesors(Profesor profesor)
        {
            base.AddObject("Profesors", profesor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Smers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSmers(Smer smer)
        {
            base.AddObject("Smers", smer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Predmets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPredmets(Predmet predmet)
        {
            base.AddObject("Predmets", predmet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentskaEvidencijaModel", Name="Ispit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ispit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ispit object.
        /// </summary>
        /// <param name="studentID">Initial value of the StudentID property.</param>
        /// <param name="predmetID">Initial value of the PredmetID property.</param>
        /// <param name="profesorID">Initial value of the ProfesorID property.</param>
        public static Ispit CreateIspit(global::System.Int32 studentID, global::System.Int32 predmetID, global::System.Int32 profesorID)
        {
            Ispit ispit = new Ispit();
            ispit.StudentID = studentID;
            ispit.PredmetID = predmetID;
            ispit.ProfesorID = profesorID;
            return ispit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                if (_StudentID != value)
                {
                    OnStudentIDChanging(value);
                    ReportPropertyChanging("StudentID");
                    _StudentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentID");
                    OnStudentIDChanged();
                }
            }
        }
        private global::System.Int32 _StudentID;
        partial void OnStudentIDChanging(global::System.Int32 value);
        partial void OnStudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PredmetID
        {
            get
            {
                return _PredmetID;
            }
            set
            {
                if (_PredmetID != value)
                {
                    OnPredmetIDChanging(value);
                    ReportPropertyChanging("PredmetID");
                    _PredmetID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PredmetID");
                    OnPredmetIDChanged();
                }
            }
        }
        private global::System.Int32 _PredmetID;
        partial void OnPredmetIDChanging(global::System.Int32 value);
        partial void OnPredmetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Datum
        {
            get
            {
                return _Datum;
            }
            set
            {
                OnDatumChanging(value);
                ReportPropertyChanging("Datum");
                _Datum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Datum");
                OnDatumChanged();
            }
        }
        private Nullable<global::System.DateTime> _Datum;
        partial void OnDatumChanging(Nullable<global::System.DateTime> value);
        partial void OnDatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ocena
        {
            get
            {
                return _Ocena;
            }
            set
            {
                OnOcenaChanging(value);
                ReportPropertyChanging("Ocena");
                _Ocena = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ocena");
                OnOcenaChanged();
            }
        }
        private Nullable<global::System.Int32> _Ocena;
        partial void OnOcenaChanging(Nullable<global::System.Int32> value);
        partial void OnOcenaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProfesorID
        {
            get
            {
                return _ProfesorID;
            }
            set
            {
                OnProfesorIDChanging(value);
                ReportPropertyChanging("ProfesorID");
                _ProfesorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfesorID");
                OnProfesorIDChanged();
            }
        }
        private global::System.Int32 _ProfesorID;
        partial void OnProfesorIDChanging(global::System.Int32 value);
        partial void OnProfesorIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Ispit_Predmet", "Predmet")]
        public Predmet Predmet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("StudentskaEvidencijaModel.FK_Ispit_Predmet", "Predmet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("StudentskaEvidencijaModel.FK_Ispit_Predmet", "Predmet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Predmet> PredmetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("StudentskaEvidencijaModel.FK_Ispit_Predmet", "Predmet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Predmet>("StudentskaEvidencijaModel.FK_Ispit_Predmet", "Predmet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Ispit_Student", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("StudentskaEvidencijaModel.FK_Ispit_Student", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("StudentskaEvidencijaModel.FK_Ispit_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("StudentskaEvidencijaModel.FK_Ispit_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("StudentskaEvidencijaModel.FK_Ispit_Student", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Ispit_Profesor", "Profesor")]
        public Profesor Profesor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("StudentskaEvidencijaModel.FK_Ispit_Profesor", "Profesor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("StudentskaEvidencijaModel.FK_Ispit_Profesor", "Profesor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profesor> ProfesorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("StudentskaEvidencijaModel.FK_Ispit_Profesor", "Profesor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profesor>("StudentskaEvidencijaModel.FK_Ispit_Profesor", "Profesor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentskaEvidencijaModel", Name="Korisnik")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Korisnik : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Korisnik object.
        /// </summary>
        /// <param name="korisnikID">Initial value of the KorisnikID property.</param>
        public static Korisnik CreateKorisnik(global::System.Int32 korisnikID)
        {
            Korisnik korisnik = new Korisnik();
            korisnik.KorisnikID = korisnikID;
            return korisnik;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KorisnikID
        {
            get
            {
                return _KorisnikID;
            }
            set
            {
                if (_KorisnikID != value)
                {
                    OnKorisnikIDChanging(value);
                    ReportPropertyChanging("KorisnikID");
                    _KorisnikID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KorisnikID");
                    OnKorisnikIDChanged();
                }
            }
        }
        private global::System.Int32 _KorisnikID;
        partial void OnKorisnikIDChanging(global::System.Int32 value);
        partial void OnKorisnikIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ime
        {
            get
            {
                return _Ime;
            }
            set
            {
                OnImeChanging(value);
                ReportPropertyChanging("Ime");
                _Ime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ime");
                OnImeChanged();
            }
        }
        private global::System.String _Ime;
        partial void OnImeChanging(global::System.String value);
        partial void OnImeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prezime
        {
            get
            {
                return _Prezime;
            }
            set
            {
                OnPrezimeChanging(value);
                ReportPropertyChanging("Prezime");
                _Prezime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prezime");
                OnPrezimeChanged();
            }
        }
        private global::System.String _Prezime;
        partial void OnPrezimeChanging(global::System.String value);
        partial void OnPrezimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KorisnickoIme
        {
            get
            {
                return _KorisnickoIme;
            }
            set
            {
                OnKorisnickoImeChanging(value);
                ReportPropertyChanging("KorisnickoIme");
                _KorisnickoIme = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KorisnickoIme");
                OnKorisnickoImeChanged();
            }
        }
        private global::System.String _KorisnickoIme;
        partial void OnKorisnickoImeChanging(global::System.String value);
        partial void OnKorisnickoImeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lozinka
        {
            get
            {
                return _Lozinka;
            }
            set
            {
                OnLozinkaChanging(value);
                ReportPropertyChanging("Lozinka");
                _Lozinka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lozinka");
                OnLozinkaChanged();
            }
        }
        private global::System.String _Lozinka;
        partial void OnLozinkaChanging(global::System.String value);
        partial void OnLozinkaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentskaEvidencijaModel", Name="Predmet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Predmet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Predmet object.
        /// </summary>
        /// <param name="predmetID">Initial value of the PredmetID property.</param>
        /// <param name="smerID">Initial value of the SmerID property.</param>
        public static Predmet CreatePredmet(global::System.Int32 predmetID, global::System.Int32 smerID)
        {
            Predmet predmet = new Predmet();
            predmet.PredmetID = predmetID;
            predmet.SmerID = smerID;
            return predmet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PredmetID
        {
            get
            {
                return _PredmetID;
            }
            set
            {
                if (_PredmetID != value)
                {
                    OnPredmetIDChanging(value);
                    ReportPropertyChanging("PredmetID");
                    _PredmetID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PredmetID");
                    OnPredmetIDChanged();
                }
            }
        }
        private global::System.Int32 _PredmetID;
        partial void OnPredmetIDChanging(global::System.Int32 value);
        partial void OnPredmetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NazivPredmeta
        {
            get
            {
                return _NazivPredmeta;
            }
            set
            {
                OnNazivPredmetaChanging(value);
                ReportPropertyChanging("NazivPredmeta");
                _NazivPredmeta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NazivPredmeta");
                OnNazivPredmetaChanged();
            }
        }
        private global::System.String _NazivPredmeta;
        partial void OnNazivPredmetaChanging(global::System.String value);
        partial void OnNazivPredmetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SmerID
        {
            get
            {
                return _SmerID;
            }
            set
            {
                OnSmerIDChanging(value);
                ReportPropertyChanging("SmerID");
                _SmerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SmerID");
                OnSmerIDChanged();
            }
        }
        private global::System.Int32 _SmerID;
        partial void OnSmerIDChanging(global::System.Int32 value);
        partial void OnSmerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Poeni
        {
            get
            {
                return _Poeni;
            }
            set
            {
                OnPoeniChanging(value);
                ReportPropertyChanging("Poeni");
                _Poeni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Poeni");
                OnPoeniChanged();
            }
        }
        private Nullable<global::System.Int32> _Poeni;
        partial void OnPoeniChanging(Nullable<global::System.Int32> value);
        partial void OnPoeniChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Ispit_Predmet", "Ispit")]
        public EntityCollection<Ispit> Ispits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ispit>("StudentskaEvidencijaModel.FK_Ispit_Predmet", "Ispit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ispit>("StudentskaEvidencijaModel.FK_Ispit_Predmet", "Ispit", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Predmet_Smer", "Smer")]
        public Smer Smer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Smer>("StudentskaEvidencijaModel.FK_Predmet_Smer", "Smer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Smer>("StudentskaEvidencijaModel.FK_Predmet_Smer", "Smer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Smer> SmerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Smer>("StudentskaEvidencijaModel.FK_Predmet_Smer", "Smer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Smer>("StudentskaEvidencijaModel.FK_Predmet_Smer", "Smer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "PredmetProfesor", "Profesor")]
        public EntityCollection<Profesor> Profesors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Profesor>("StudentskaEvidencijaModel.PredmetProfesor", "Profesor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Profesor>("StudentskaEvidencijaModel.PredmetProfesor", "Profesor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentskaEvidencijaModel", Name="Profesor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profesor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profesor object.
        /// </summary>
        /// <param name="profesorID">Initial value of the ProfesorID property.</param>
        public static Profesor CreateProfesor(global::System.Int32 profesorID)
        {
            Profesor profesor = new Profesor();
            profesor.ProfesorID = profesorID;
            return profesor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProfesorID
        {
            get
            {
                return _ProfesorID;
            }
            set
            {
                if (_ProfesorID != value)
                {
                    OnProfesorIDChanging(value);
                    ReportPropertyChanging("ProfesorID");
                    _ProfesorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProfesorID");
                    OnProfesorIDChanged();
                }
            }
        }
        private global::System.Int32 _ProfesorID;
        partial void OnProfesorIDChanging(global::System.Int32 value);
        partial void OnProfesorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImePrezime
        {
            get
            {
                return _ImePrezime;
            }
            set
            {
                OnImePrezimeChanging(value);
                ReportPropertyChanging("ImePrezime");
                _ImePrezime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImePrezime");
                OnImePrezimeChanged();
            }
        }
        private global::System.String _ImePrezime;
        partial void OnImePrezimeChanging(global::System.String value);
        partial void OnImePrezimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GodinaZaposlenja
        {
            get
            {
                return _GodinaZaposlenja;
            }
            set
            {
                OnGodinaZaposlenjaChanging(value);
                ReportPropertyChanging("GodinaZaposlenja");
                _GodinaZaposlenja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GodinaZaposlenja");
                OnGodinaZaposlenjaChanged();
            }
        }
        private Nullable<global::System.Int32> _GodinaZaposlenja;
        partial void OnGodinaZaposlenjaChanging(Nullable<global::System.Int32> value);
        partial void OnGodinaZaposlenjaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "PredmetProfesor", "Predmet")]
        public EntityCollection<Predmet> Predmets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Predmet>("StudentskaEvidencijaModel.PredmetProfesor", "Predmet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Predmet>("StudentskaEvidencijaModel.PredmetProfesor", "Predmet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Ispit_Profesor", "Ispit")]
        public EntityCollection<Ispit> Ispits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ispit>("StudentskaEvidencijaModel.FK_Ispit_Profesor", "Ispit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ispit>("StudentskaEvidencijaModel.FK_Ispit_Profesor", "Ispit", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentskaEvidencijaModel", Name="Smer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Smer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Smer object.
        /// </summary>
        /// <param name="smerID">Initial value of the SmerID property.</param>
        public static Smer CreateSmer(global::System.Int32 smerID)
        {
            Smer smer = new Smer();
            smer.SmerID = smerID;
            return smer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SmerID
        {
            get
            {
                return _SmerID;
            }
            set
            {
                if (_SmerID != value)
                {
                    OnSmerIDChanging(value);
                    ReportPropertyChanging("SmerID");
                    _SmerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SmerID");
                    OnSmerIDChanged();
                }
            }
        }
        private global::System.Int32 _SmerID;
        partial void OnSmerIDChanging(global::System.Int32 value);
        partial void OnSmerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NazivSmera
        {
            get
            {
                return _NazivSmera;
            }
            set
            {
                OnNazivSmeraChanging(value);
                ReportPropertyChanging("NazivSmera");
                _NazivSmera = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NazivSmera");
                OnNazivSmeraChanged();
            }
        }
        private global::System.String _NazivSmera;
        partial void OnNazivSmeraChanging(global::System.String value);
        partial void OnNazivSmeraChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Predmet_Smer", "Predmet")]
        public EntityCollection<Predmet> Predmets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Predmet>("StudentskaEvidencijaModel.FK_Predmet_Smer", "Predmet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Predmet>("StudentskaEvidencijaModel.FK_Predmet_Smer", "Predmet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Student_Smer", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("StudentskaEvidencijaModel.FK_Student_Smer", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("StudentskaEvidencijaModel.FK_Student_Smer", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentskaEvidencijaModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentID">Initial value of the StudentID property.</param>
        /// <param name="smerID">Initial value of the SmerID property.</param>
        public static Student CreateStudent(global::System.Int32 studentID, global::System.Int32 smerID)
        {
            Student student = new Student();
            student.StudentID = studentID;
            student.SmerID = smerID;
            return student;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                if (_StudentID != value)
                {
                    OnStudentIDChanging(value);
                    ReportPropertyChanging("StudentID");
                    _StudentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentID");
                    OnStudentIDChanged();
                }
            }
        }
        private global::System.Int32 _StudentID;
        partial void OnStudentIDChanging(global::System.Int32 value);
        partial void OnStudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImePrezime
        {
            get
            {
                return _ImePrezime;
            }
            set
            {
                OnImePrezimeChanging(value);
                ReportPropertyChanging("ImePrezime");
                _ImePrezime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImePrezime");
                OnImePrezimeChanged();
            }
        }
        private global::System.String _ImePrezime;
        partial void OnImePrezimeChanging(global::System.String value);
        partial void OnImePrezimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BrojIndeksa
        {
            get
            {
                return _BrojIndeksa;
            }
            set
            {
                OnBrojIndeksaChanging(value);
                ReportPropertyChanging("BrojIndeksa");
                _BrojIndeksa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BrojIndeksa");
                OnBrojIndeksaChanged();
            }
        }
        private global::System.String _BrojIndeksa;
        partial void OnBrojIndeksaChanging(global::System.String value);
        partial void OnBrojIndeksaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Finansiranje
        {
            get
            {
                return _Finansiranje;
            }
            set
            {
                OnFinansiranjeChanging(value);
                ReportPropertyChanging("Finansiranje");
                _Finansiranje = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Finansiranje");
                OnFinansiranjeChanged();
            }
        }
        private global::System.String _Finansiranje;
        partial void OnFinansiranjeChanging(global::System.String value);
        partial void OnFinansiranjeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Slika
        {
            get
            {
                return _Slika;
            }
            set
            {
                OnSlikaChanging(value);
                ReportPropertyChanging("Slika");
                _Slika = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Slika");
                OnSlikaChanged();
            }
        }
        private global::System.String _Slika;
        partial void OnSlikaChanging(global::System.String value);
        partial void OnSlikaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SmerID
        {
            get
            {
                return _SmerID;
            }
            set
            {
                OnSmerIDChanging(value);
                ReportPropertyChanging("SmerID");
                _SmerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SmerID");
                OnSmerIDChanged();
            }
        }
        private global::System.Int32 _SmerID;
        partial void OnSmerIDChanging(global::System.Int32 value);
        partial void OnSmerIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Ispit_Student", "Ispit")]
        public EntityCollection<Ispit> Ispits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ispit>("StudentskaEvidencijaModel.FK_Ispit_Student", "Ispit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ispit>("StudentskaEvidencijaModel.FK_Ispit_Student", "Ispit", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentskaEvidencijaModel", "FK_Student_Smer", "Smer")]
        public Smer Smer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Smer>("StudentskaEvidencijaModel.FK_Student_Smer", "Smer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Smer>("StudentskaEvidencijaModel.FK_Student_Smer", "Smer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Smer> SmerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Smer>("StudentskaEvidencijaModel.FK_Student_Smer", "Smer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Smer>("StudentskaEvidencijaModel.FK_Student_Smer", "Smer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentskaEvidencijaModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
